//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        public int IDItem { get; set; }
        public string Name { get; set; }
        public Nullable<int> Balance { get; set; }
        public string Type { get; set; }
        public Nullable<long> Cost { get; set; }
        public string Color { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> IDOrder { get; set; }
        public Nullable<int> IDType { get; set; }
    
        public virtual ItemsType ItemsType { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
